widgetTheme=widget-themes/original
primaryColor=#33C4B6
secondaryColor=#FA7A00
labelColor=#ffffff
hideWhenOffline=false
contactMail=kyang1@sbec.com
loadingLabel=Loading...
loginError=Login error
chatHeader=Talk to us
startInfo=填写一下信息开始聊天吧
widgetWidth=370
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Start
backLabel=Back
initMessageBody=您好，请问您需要帮助吗？
initMessageAuthor=小助手
chatInputLabel=Write your question
timeDaysAgo=day(s) ago
timeHoursAgo=hour(s) ago
timeMinutesAgo=minute(s) ago
timeSecondsAgo=second(s) ago
offlineMessage=小助手不在线
toggleSoundLabel=Sound effects
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Toggle fullscreen
endChatLabel=结束通话
endChatConfirmQuestion=您确定结束通话？
endChatConfirm=是的
endChatCancel=取消
contactHeader=联系我们
contactInfo=小助手睡觉去了，有问题的话发封邮件来吧！
contactNameLabel=姓名
contactMailLabel=微信号或邮箱
contactQuestionLabel=您的问题
contactSendLabel=发送
contactSuccessHeader=已发送
contactSuccessMessage=感谢您的问题。
contactErrorHeader=Error
contactErrorMessage=出错了哦！
headerHeight=55
installed=1
autoShowWidgetAfter=10
autoShowWidget=true
askForMail=true
notificationIcon=img/notification.png
